USE mydatabase;

CREATE TABLE IF NOT EXISTS `emails` (
  `EmailID` INT AUTO_INCREMENT PRIMARY KEY,
  `id` VARCHAR(255) DEFAULT NULL,
  `Source` VARCHAR(255) DEFAULT 'N8N Flow',
  `WrittenDateTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `sender_name` VARCHAR(255) DEFAULT NULL,
  `sender_email` VARCHAR(255) DEFAULT NULL,
  `recipient` VARCHAR(255) DEFAULT NULL,
  `subject` VARCHAR(255) DEFAULT NULL,
  `snippet` VARCHAR(255) DEFAULT NULL,
  `labels` VARCHAR(255) DEFAULT NULL,
  `body` LONGTEXT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
